'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Login

    '''<summary>
    '''lbl_CRS_Login_Title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_CRS_Login_Title As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_CRS_Login_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_CRS_Login_Name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_CRS_Login_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_CRS_Login_Name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_CRS_Login_Password control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_CRS_Login_Password As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_CRS_Login_Password control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_CRS_Login_Password As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_CRS_Login control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_CRS_Login As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_CRS_Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_CRS_Status As Global.System.Web.UI.WebControls.Label
End Class
