'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class reporting

    '''<summary>
    '''scrManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents scrManager As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''pnlUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlUpdate As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''pnl_Welcome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_Welcome As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnl_Referral_Feedback control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_Referral_Feedback As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblReferralFeedbackFirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReferralFeedbackFirm As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblReferralFeedbackAttorney control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReferralFeedbackAttorney As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCase As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCaseInformation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCaseInformation As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rdoAre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdoAre As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rdoAreNot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdoAreNot As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReason As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnReferralFeedbackWellTakeThisCase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReferralFeedbackWellTakeThisCase As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnReferralFeedbackGiveThisCaseToSomeoneElse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReferralFeedbackGiveThisCaseToSomeoneElse As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnl_Case_Reporting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_Case_Reporting As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblCaseReportingFirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCaseReportingFirm As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCaseReportingAttorney control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCaseReportingAttorney As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCaseReportingClientName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCaseReportingClientName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCaseReportingClientID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCaseReportingClientID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCaseReportingMainCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCaseReportingMainCategory As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCaseReportingTypeOfCase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCaseReportingTypeOfCase As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCaseReportingComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCaseReportingComments As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCaseReportingComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCaseReportingComments As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnCaseReportingComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCaseReportingComments As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblCaseReportingCommentsSaved control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCaseReportingCommentsSaved As Global.System.Web.UI.WebControls.Label
End Class
